using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Manhood
{
    /// <summary>
    /// Stores information about a Manhood interpreter error.
    /// </summary>
    public class Error
    {
        private int _line, _col, _index;
        private string _message;
        private ErrorType _errType;

        /// <summary>
        /// Gets the zero-based line number at which the error occurs.
        /// </summary>
        public int Line
        {
            get { return _line; }
        }

        /// <summary>
        /// Gets the zero-based column number within the line at which the errors occurs.
        /// </summary>
        public int Column
        {
            get { return _col; }
        }

        /// <summary>
        /// Gets the zero-based character index at which the errors occurs.
        /// </summary>
        public int Index
        {
            get { return _index; }
        }

        /// <summary>
        /// Gets the type of error.
        /// </summary>
        public ErrorType Type
        {
            get { return _errType; }
        }

        /// <summary>
        /// Gets the error message generated by the engine.
        /// </summary>
        public string Message
        {
            get { return _message; }
        }

        internal Error(ErrorType type, int line, int col, int index, string msg, params object[] args)
        {
            _line = line;
            _col = col;
            _index = index;
            _errType = type;
            try
            {
                _message = String.Format(msg, args);
            }
            catch (Exception ex)
            {
                _message = msg;
            }
            
        }

        /// <summary>
        /// Returns a string representation of the error with a one-based line and column.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("{0} (Line {1}, Col {2}): ", _errType, _line + 1, _col + 1) + _message;
        }
    }
}
